### PR TITLE
Implement optionalDeep add migration notice

### PR DESCRIPTION
**Pull request by indykoning**
BREAKING

Since optionalDeep will always return the optional class we explicitly need to ask it if a value is set
```diff
- @if($globals->cookie_notice->text)
+ @if($globals->cookie_notice->text->isset())
```

This also means that checks for specific values need to be updated
```diff
- @if($globals->cookie_notice->text === 'foo')
+ @if($globals->cookie_notice->text->get() === 'foo')
```

### CODE REVIEW

**Comment by royduin** [comment]
Looking good! But your first example should still work?
```
@if($globals->cookie_notice->text)
```
If something doesn't exist it should return `null` right?

**Comment by royduin** [comment]
Can't we somehow force `__toString()`?

**Comment by Jade-GG** [comment]
> Can't we somehow force `__toString()`?

No, but you can always explicitly do it. The only way to theoretically have it work like this without a function is by abusing [simplexmlelement](https://www.php.net/manual/en/class.simplexmlelement.php), and having an expression turning it into a falsy xml element, that php will then parse into `false`. As you can imagine, this is not a proper solution and will not work for arbirtary objects like this.

**Comment by Jade-GG** [comment]
It's been 15 years since [this original __toBoolean() proposal was rejected](https://externals.io/message/39323#39331) and it seems like a [currently open RFC](https://wiki.php.net/rfc/objects-can-be-falsifiable) also isn't going anywhere.

**Comment by royduin** [comment]
Bummer, merged. Let's see how this turns out in projects.

**Pull request merged**
